# -Denv=dev -Dapollo.cluster=DEFAULT -Dserver.port=53050
app:
  id: account-service
apollo:
  bootstrap:
    enabled: true
    namespaces: application,micro_service.spring-boot-druid,micro_service.spring-boot-http,micro_service.spring-eureka,micro_service.spring-hystrix,micro_service.spring-ribbon,micro_service.spring-boot-redis,micro_service.mybatis-plus,micro_service.spring-rocketmq

spring:
  application:
    name: account-service
  datasource:

logging:
  config: classpath:log4j2-dev.xml
  level:
    cn.itcast.wanxinp2p.account.mapper: debug

swagger:
  base-package:cn.itcast.wanxinp2p






